create extension if not exists "uuid-ossp";

create table if not exists country
(
    id                      UUID unique             not null default uuid_generate_v1(),
    code                    varchar(10)     unique  not null,
    name                    varchar(255)    unique  not null,
    primary key (id)
);

alter table country
    owner to postgres;


delete from country;

insert into country(name, code) values ('Fiji','FJ');
insert into country(name, code) values ('Tanzania','TZ');
insert into country(name, code) values ('Western Sahara','EH');
insert into country(name, code) values ('Canada','CA');
insert into country(name, code) values ('United States','US');
insert into country(name, code) values ('Kazakhstan','KZ');
insert into country(name, code) values ('Uzbekistan','UZ');
insert into country(name, code) values ('Papua New Guinea','PG');
insert into country(name, code) values ('Indonesia','ID');
insert into country(name, code) values ('Argentina','AR');
insert into country(name, code) values ('Chile','CL');
insert into country(name, code) values ('Democratic Republic of the Congo','CD');
insert into country(name, code) values ('Somalia','SO');
insert into country(name, code) values ('Kenya','KE');
insert into country(name, code) values ('Sudan','SD');
insert into country(name, code) values ('Chad','TD');
insert into country(name, code) values ('Haiti','HT');
insert into country(name, code) values ('Dominican Republic','DO');
insert into country(name, code) values ('Russia','RU');
insert into country(name, code) values ('Bahamas','BS');
insert into country(name, code) values ('Falkland Islands','FK');
insert into country(name, code) values ('Norway','NO');
insert into country(name, code) values ('Greenland','GL');
insert into country(name, code) values ('Timor-Leste','TL');
insert into country(name, code) values ('South Africa','ZA');
insert into country(name, code) values ('Lesotho','LS');
insert into country(name, code) values ('Mexico','MX');
insert into country(name, code) values ('Uruguay','UY');
insert into country(name, code) values ('Brazil','BR');
insert into country(name, code) values ('Bolivia','BO');
insert into country(name, code) values ('Peru','PE');
insert into country(name, code) values ('Colombia','CO');
insert into country(name, code) values ('Panama','PA');
insert into country(name, code) values ('Costa Rica','CR');
insert into country(name, code) values ('Nicaragua','NI');
insert into country(name, code) values ('Honduras','HN');
insert into country(name, code) values ('El Salvador','SV');
insert into country(name, code) values ('Guatemala','GT');
insert into country(name, code) values ('Belize','BZ');
insert into country(name, code) values ('Venezuela','VE');
insert into country(name, code) values ('Guyana','GY');
insert into country(name, code) values ('Suriname','SR');
insert into country(name, code) values ('France','FR');
insert into country(name, code) values ('Ecuador','EC');
insert into country(name, code) values ('Puerto Rico','PR');
insert into country(name, code) values ('Jamaica','JM');
insert into country(name, code) values ('Cuba','CU');
insert into country(name, code) values ('Zimbabwe','ZW');
insert into country(name, code) values ('Botswana','BW');
insert into country(name, code) values ('Namibia','NA');
insert into country(name, code) values ('Senegal','SN');
insert into country(name, code) values ('Mali','ML');
insert into country(name, code) values ('Mauritania','MR');
insert into country(name, code) values ('Benin','BJ');
insert into country(name, code) values ('Niger','NE');
insert into country(name, code) values ('Nigeria','NG');
insert into country(name, code) values ('Cameroon','CM');
insert into country(name, code) values ('Togo','TG');
insert into country(name, code) values ('Ghana','GH');
insert into country(name, code) values ('Côted"Ivoire','CI');
insert into country(name, code) values ('Guinea','GN');
insert into country(name, code) values ('Guinea-Bissau','GW');
insert into country(name, code) values ('Liberia','LR');
insert into country(name, code) values ('Sierra Leone','SL');
insert into country(name, code) values ('Burkina Faso','BF');
insert into country(name, code) values ('Central African Republic','CF');
insert into country(name, code) values ('Republic of the Congo','CG');
insert into country(name, code) values ('Gabon','GA');
insert into country(name, code) values ('Equatorial Guinea','GQ');
insert into country(name, code) values ('Zambia','ZM');
insert into country(name, code) values ('Malawi','MW');
insert into country(name, code) values ('Mozambique','MZ');
insert into country(name, code) values ('Eswatini','SZ');
insert into country(name, code) values ('Angola','AO');
insert into country(name, code) values ('Burundi','BI');
insert into country(name, code) values ('Israel','IL');
insert into country(name, code) values ('Lebanon','LB');
insert into country(name, code) values ('Madagascar','MG');
insert into country(name, code) values ('Palestine','PS');
insert into country(name, code) values ('The Gambia','GM');
insert into country(name, code) values ('Tunisia','TN');
insert into country(name, code) values ('Algeria','DZ');
insert into country(name, code) values ('Jordan','JO');
insert into country(name, code) values ('United Arab Emirates','AE');
insert into country(name, code) values ('Qatar','QA');
insert into country(name, code) values ('Kuwait','KW');
insert into country(name, code) values ('Iraq','IQ');
insert into country(name, code) values ('Oman','OM');
insert into country(name, code) values ('Vanuatu','VU');
insert into country(name, code) values ('Cambodia','KH');
insert into country(name, code) values ('Thailand','TH');
insert into country(name, code) values ('Lao PDR','LA');
insert into country(name, code) values ('Myanmar','MM');
insert into country(name, code) values ('Vietnam','VN');
insert into country(name, code) values ('Dem. Rep. Korea','KP');
insert into country(name, code) values ('Republic of Korea','KR');
insert into country(name, code) values ('Mongolia','MN');
insert into country(name, code) values ('India','IN');
insert into country(name, code) values ('Bangladesh','BD');
insert into country(name, code) values ('Bhutan','BT');
insert into country(name, code) values ('Nepal','NP');
insert into country(name, code) values ('Pakistan','PK');
insert into country(name, code) values ('Afghanistan','AF');
insert into country(name, code) values ('Tajikistan','TJ');
insert into country(name, code) values ('Kyrgyzstan','KG');
insert into country(name, code) values ('Turkmenistan','TM');
insert into country(name, code) values ('Iran','IR');
insert into country(name, code) values ('Syria','SY');
insert into country(name, code) values ('Armenia','AM');
insert into country(name, code) values ('Sweden','SE');
insert into country(name, code) values ('Belarus','BY');
insert into country(name, code) values ('Ukraine','UA');
insert into country(name, code) values ('Poland','PL');
insert into country(name, code) values ('Austria','AT');
insert into country(name, code) values ('Hungary','HU');
insert into country(name, code) values ('Moldova','MD');
insert into country(name, code) values ('Romania','RO');
insert into country(name, code) values ('Lithuania','LT');
insert into country(name, code) values ('Latvia','LV');
insert into country(name, code) values ('Estonia','EE');
insert into country(name, code) values ('Germany','DE');
insert into country(name, code) values ('Bulgaria','BG');
insert into country(name, code) values ('Greece','GR');
insert into country(name, code) values ('Turkey','TR');
insert into country(name, code) values ('Albania','AL');
insert into country(name, code) values ('Croatia','HR');
insert into country(name, code) values ('Switzerland','CH');
insert into country(name, code) values ('Luxembourg','LU');
insert into country(name, code) values ('Belgium','BE');
insert into country(name, code) values ('Netherlands','NL');
insert into country(name, code) values ('Portugal','PT');
insert into country(name, code) values ('Spain','ES');
insert into country(name, code) values ('Ireland','IE');
insert into country(name, code) values ('New Caledonia','NC');
insert into country(name, code) values ('Solomon Islands','SB');
insert into country(name, code) values ('New Zealand','NZ');
insert into country(name, code) values ('Australia','AU');
insert into country(name, code) values ('Sri Lanka','LK');
insert into country(name, code) values ('China','CN');
insert into country(name, code) values ('Taiwan','TW');
insert into country(name, code) values ('Italy','IT');
insert into country(name, code) values ('Denmark','DK');
insert into country(name, code) values ('United Kingdom','GB');
insert into country(name, code) values ('Iceland','IS');
insert into country(name, code) values ('Azerbaijan','AZ');
insert into country(name, code) values ('Georgia','GE');
insert into country(name, code) values ('Philippines','PH');
insert into country(name, code) values ('Malaysia','MY');
insert into country(name, code) values ('Brunei Darussalam','BN');
insert into country(name, code) values ('Slovenia','SI');
insert into country(name, code) values ('Finland','FI');
insert into country(name, code) values ('Slovakia','SK');
insert into country(name, code) values ('Czech Republic','CZ');
insert into country(name, code) values ('Eritrea','ER');
insert into country(name, code) values ('Japan','JP');
insert into country(name, code) values ('Paraguay','PY');
insert into country(name, code) values ('Yemen','YE');
insert into country(name, code) values ('Saudi Arabia','SA');
insert into country(name, code) values ('Northern Cyprus','CYP');
insert into country(name, code) values ('Cyprus','CY');
insert into country(name, code) values ('Morocco','MA');
insert into country(name, code) values ('Egypt','EG');
insert into country(name, code) values ('Libya','LY');
insert into country(name, code) values ('Ethiopia','ET');
insert into country(name, code) values ('Djibouti','DJ');
insert into country(name, code) values ('Somaliland','SOM');
insert into country(name, code) values ('Uganda','UG');
insert into country(name, code) values ('Rwanda','RW');
insert into country(name, code) values ('Bosnia and Herzegovina','BA');
insert into country(name, code) values ('Macedonia','MK');
insert into country(name, code) values ('Serbia','RS');
insert into country(name, code) values ('Montenegro','ME');
insert into country(name, code) values ('Kosovo','XK');
insert into country(name, code) values ('Trinidad and Tobago','TT');
insert into country(name, code) values ('South Sudan','SS');